image: node:10.22.0-alpine

pages:
  cache:
    paths:
      - node_modules

  script:
    - apk -U upgrade && apk add -t build-dependencies build-base python
    - yarn install --pure-lockfile
    - yarn build
    - rm -rf public && mv build public

  artifacts:
    paths:
      - public

  only:
    - master
